export const HOME_STAGES = [
  'CAPTURE THE FUTURE',
  'CAPTURED THE MOMENT',
  'MOMENT EDITED',
  'FRAME PERFECTED',
  'STORY PRESERVED',
]

export const DRONE_STAGES = [
  'SEE THE WORLD DIFFERENTLY',
  'ABOVE THE HORIZON',
  'AERIAL PERSPECTIVE',
  'BEYOND THE FRAME',
  'SKY IS THE CANVAS',
]

export const WEDDING_STAGES = [
  'FOREVER STARTS HERE',
  'EVERY MEMORY MATTERS',
  'LOVE IN MOTION',
  'CINEMATIC LOVE STORIES',
  'MEMORIES THAT LIVE FOREVER',
]

export const EVENTS_STAGES = [
  'EXPERIENCE THE ENERGY',
  'EVERY EVENT DESERVES A STORY',
  'LIGHTS. CROWD. CINEMA.',
  'MOMENTS THAT MOVE PEOPLE',
  'LIVE THE EXPERIENCE',
]

export const ABOUT_STAGES = [
  'IDEAS TO IMPACT',
  'CREATIVITY MEETS SYSTEMS',
  'BUILT FOR MODERN BRANDS',
  'STORYTELLING THROUGH MOTION',
  'CINEMATIC DIGITAL EXPERIENCES',
]
