export const HOME_STAGES = [
  'COMMERCIAL & EVENTS\nPHOTOGRAPHY',
  'WHERE LOVE\nSHINES',
  'LOVE. LIGHT.\nLEGACY.',
  'AERIAL & COMMERCIAL\nPPHOTOGRAPHY',
  
]

export const DRONE_STAGES = [
  'SEE THE WORLD DIFFERENTLY',
  'ABOVE THE HORIZON',
  'AERIAL PERSPECTIVE',
  'BEYOND THE FRAME',
  'SKY IS THE CANVAS',
]

export const WEDDING_STAGES = [
  'FOREVER STARTS\nHERE',
  'EVERY MEMORY\nMATTERS',
  'LOVE IN\nMOTION',
  'CINEMATIC LOVE\nSTORIES',
  'MEMORIES THAT\nLIVE FOREVER',
]

export const EVENTS_STAGES = [
  'EXPERIENCE THE \nENERGY',
  'EVERY EVENT \nDESERVES A STORY',
  'LIGHTS. CROWD. CINEMA.',
  'COMMERCIAL BRAND \nEXHIBITIONS',
  'COMMERCIAL BRAND\n AD SHOOT',
]

export const ABOUT_STAGES = [
  'IDEAS TO IMPACT',
  'CREATIVITY MEETS SYSTEMS',
  'BUILT FOR MODERN BRANDS',
  'STORYTELLING THROUGH MOTION',
  'CINEMATIC DIGITAL EXPERIENCES',
]
