export const HOME_STAGES = [
  'MOMENTS INTO\nMEMORIES',
  'WHERE LOVE\nSHINES',
  'LOVE. LIGHT.\nLEGACY.',
  'CRAFTING YOUR\nLEGACY',
  
]

export const DRONE_STAGES = [
  'SEE THE WORLD DIFFERENTLY',
  'ABOVE THE HORIZON',
  'AERIAL PERSPECTIVE',
  'BEYOND THE FRAME',
  'SKY IS THE CANVAS',
]

export const WEDDING_STAGES = [
   'FOREVER STARTS\nHERE',
  'EVERY MEMORY\nMATTERS',
  'LOVE IN\nMOTION',
  'CINEMATIC LOVE\nSTORIES',
  'MEMORIES THAT\nLIVE FOREVER',
]

export const EVENTS_STAGES = [
  'EXPERIENCE THE \nENERGY',
  'EVERY EVENT \nDESERVES A STORY',
  'LIGHTS. CROWD. CINEMA.',
  'MOMENTS THAT \nMOVE PEOPLE',
  'LIVE THE EXPERIENCE',
]

export const ABOUT_STAGES = [
  'IDEAS TO IMPACT',
  'CREATIVITY MEETS SYSTEMS',
  'BUILT FOR MODERN BRANDS',
  'STORYTELLING THROUGH MOTION',
  'CINEMATIC DIGITAL EXPERIENCES',
]
